/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Company: { // root type
    companyName?: string | null; // String
    id?: string | null; // ID
    jobPosts?: Array<NexusGenRootTypes['JobPost'] | null> | null; // [JobPost]
  }
  HowToApply: { // root type
    html?: string | null; // String
    id?: string | null; // ID
    jobDetails?: NexusGenRootTypes['JobDetails'] | null; // JobDetails
    jobDetailsId?: string | null; // String
    text?: string | null; // String
  }
  Invoice: { // root type
    companyInvoiceEmail?: string | null; // String
    emailListToSendInvoice?: string | null; // String
    id?: string | null; // ID
    invoiceAddress?: string | null; // String
    invoiceNotesPurchaseOrder?: string | null; // String
    jobPost?: Array<NexusGenRootTypes['JobPost'] | null> | null; // [JobPost]
    jobPostId?: string | null; // String
    payLater?: boolean | null; // Boolean
  }
  JobDescription: { // root type
    html?: string | null; // String
    id?: string | null; // ID
    jobDetails?: NexusGenRootTypes['JobDetails'] | null; // JobDetails
    jobDetailsId?: string | null; // String
    text?: string | null; // String
  }
  JobDetails: { // root type
    applyEmail?: string | null; // String
    applyURL?: string | null; // String
    companyLogo?: string | null; // String
    highlightWithCompanyColor?: boolean | null; // Boolean
    howToApply?: Array<NexusGenRootTypes['HowToApply'] | null> | null; // [HowToApply]
    id?: string | null; // ID
    jobDescription?: Array<NexusGenRootTypes['JobDescription'] | null> | null; // [JobDescription]
    jobPost?: Array<NexusGenRootTypes['JobPost'] | null> | null; // [JobPost]
    maxAnnualSalary?: number | null; // Int
    minAnnualSalary?: number | null; // Int
  }
  JobPost: { // root type
    company?: Array<NexusGenRootTypes['Company'] | null> | null; // [Company]
    companyId?: Array<NexusGenRootTypes['Company'] | null> | null; // [Company]
    content?: string | null; // String
    emailToCandidates?: boolean | null; // Boolean
    getMatches?: boolean | null; // Boolean
    highlightPost?: boolean | null; // Boolean
    id?: string | null; // ID
    invoice?: Array<NexusGenRootTypes['Invoice'] | null> | null; // [Invoice]
    jobDetails?: Array<NexusGenRootTypes['JobDetails'] | null> | null; // [JobDetails]
    jobLocation?: string | null; // String
    jobPostDuration?: number | null; // Int
    position?: string | null; // String
    positionType?: string | null; // String
    primaryTag?: string | null; // String
    published?: boolean | null; // Boolean
    showCompanyLogo?: boolean | null; // Boolean
    stickForDuration?: number | null; // Int
    tags?: Array<string | null> | null; // [String]
    title?: string | null; // String
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Company: { // field return type
    companyName: string | null; // String
    id: string | null; // ID
    jobPosts: Array<NexusGenRootTypes['JobPost'] | null> | null; // [JobPost]
  }
  HowToApply: { // field return type
    html: string | null; // String
    id: string | null; // ID
    jobDetails: NexusGenRootTypes['JobDetails'] | null; // JobDetails
    jobDetailsId: string | null; // String
    text: string | null; // String
  }
  Invoice: { // field return type
    companyInvoiceEmail: string | null; // String
    emailListToSendInvoice: string | null; // String
    id: string | null; // ID
    invoiceAddress: string | null; // String
    invoiceNotesPurchaseOrder: string | null; // String
    jobPost: Array<NexusGenRootTypes['JobPost'] | null> | null; // [JobPost]
    jobPostId: string | null; // String
    payLater: boolean | null; // Boolean
  }
  JobDescription: { // field return type
    html: string | null; // String
    id: string | null; // ID
    jobDetails: NexusGenRootTypes['JobDetails'] | null; // JobDetails
    jobDetailsId: string | null; // String
    text: string | null; // String
  }
  JobDetails: { // field return type
    applyEmail: string | null; // String
    applyURL: string | null; // String
    companyLogo: string | null; // String
    highlightWithCompanyColor: boolean | null; // Boolean
    howToApply: Array<NexusGenRootTypes['HowToApply'] | null> | null; // [HowToApply]
    id: string | null; // ID
    jobDescription: Array<NexusGenRootTypes['JobDescription'] | null> | null; // [JobDescription]
    jobPost: Array<NexusGenRootTypes['JobPost'] | null> | null; // [JobPost]
    maxAnnualSalary: number | null; // Int
    minAnnualSalary: number | null; // Int
  }
  JobPost: { // field return type
    company: Array<NexusGenRootTypes['Company'] | null> | null; // [Company]
    companyId: Array<NexusGenRootTypes['Company'] | null> | null; // [Company]
    content: string | null; // String
    emailToCandidates: boolean | null; // Boolean
    getMatches: boolean | null; // Boolean
    highlightPost: boolean | null; // Boolean
    id: string | null; // ID
    invoice: Array<NexusGenRootTypes['Invoice'] | null> | null; // [Invoice]
    jobDetails: Array<NexusGenRootTypes['JobDetails'] | null> | null; // [JobDetails]
    jobLocation: string | null; // String
    jobPostDuration: number | null; // Int
    position: string | null; // String
    positionType: string | null; // String
    primaryTag: string | null; // String
    published: boolean | null; // Boolean
    showCompanyLogo: boolean | null; // Boolean
    stickForDuration: number | null; // Int
    tags: Array<string | null> | null; // [String]
    title: string | null; // String
  }
  Mutation: { // field return type
    createCompany: NexusGenRootTypes['Company'] | null; // Company
    createJobPost: NexusGenRootTypes['JobPost'] | null; // JobPost
    deleteCompany: NexusGenRootTypes['Company'] | null; // Company
    editCompany: NexusGenRootTypes['Company'] | null; // Company
  }
  Query: { // field return type
    companies: Array<NexusGenRootTypes['Company'] | null>; // [Company]!
  }
}

export interface NexusGenFieldTypeNames {
  Company: { // field return type name
    companyName: 'String'
    id: 'ID'
    jobPosts: 'JobPost'
  }
  HowToApply: { // field return type name
    html: 'String'
    id: 'ID'
    jobDetails: 'JobDetails'
    jobDetailsId: 'String'
    text: 'String'
  }
  Invoice: { // field return type name
    companyInvoiceEmail: 'String'
    emailListToSendInvoice: 'String'
    id: 'ID'
    invoiceAddress: 'String'
    invoiceNotesPurchaseOrder: 'String'
    jobPost: 'JobPost'
    jobPostId: 'String'
    payLater: 'Boolean'
  }
  JobDescription: { // field return type name
    html: 'String'
    id: 'ID'
    jobDetails: 'JobDetails'
    jobDetailsId: 'String'
    text: 'String'
  }
  JobDetails: { // field return type name
    applyEmail: 'String'
    applyURL: 'String'
    companyLogo: 'String'
    highlightWithCompanyColor: 'Boolean'
    howToApply: 'HowToApply'
    id: 'ID'
    jobDescription: 'JobDescription'
    jobPost: 'JobPost'
    maxAnnualSalary: 'Int'
    minAnnualSalary: 'Int'
  }
  JobPost: { // field return type name
    company: 'Company'
    companyId: 'Company'
    content: 'String'
    emailToCandidates: 'Boolean'
    getMatches: 'Boolean'
    highlightPost: 'Boolean'
    id: 'ID'
    invoice: 'Invoice'
    jobDetails: 'JobDetails'
    jobLocation: 'String'
    jobPostDuration: 'Int'
    position: 'String'
    positionType: 'String'
    primaryTag: 'String'
    published: 'Boolean'
    showCompanyLogo: 'Boolean'
    stickForDuration: 'Int'
    tags: 'String'
    title: 'String'
  }
  Mutation: { // field return type name
    createCompany: 'Company'
    createJobPost: 'JobPost'
    deleteCompany: 'Company'
    editCompany: 'Company'
  }
  Query: { // field return type name
    companies: 'Company'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createCompany: { // args
      companyName?: string | null; // String
    }
    createJobPost: { // args
      content?: string | null; // String
      jobLocation?: string | null; // String
      jobPostDuration?: number | null; // Int
      position?: string | null; // String
      positionType?: string | null; // String
      primaryTag?: string | null; // String
      stickForDuration?: number | null; // Int
      title?: string | null; // String
    }
    deleteCompany: { // args
      companyId: string; // String!
    }
    editCompany: { // args
      companyId: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}